version: '2'
services:
 rabbitmq:
   image: rabbitmq:3-management
   restart: always
   ports:
#    - "5672:5672"
     - "15672:15672"

 discovery:
   build: microservices/support/discovery-server
   restart: always
   ports:
     - "8761:8761"

 config:
   build: microservices/support/config-server
   restart: always
   ports:
     - "8888:8888"

 auth:
   build: microservices/support/auth-server
   restart: always
   ports:
     - "9999:9999"

#turbine:
#  image: shubham1436/ms-blog-turbine
##  volumes:
##    - $PWD/logs:/logs
#  links:
#    - rabbitmq
#    - config

 pro:
   build: microservices/core/product-service
   restart: always
   #  volumes:
   #  - $PWD/logs:/logs
   #  - statsd

 rec:
   build: microservices/core/recommendation-service
   restart: always
#  volumes:
#    - $PWD/logs:/logs
#    - statsd

 rev:
   build: microservices/core/review-service
   restart: always
#  volumes:
#    - $PWD/logs:/logs
#    - statsd
 composite:
   build: microservices/composite/product-composite-service
   restart: always
#  volumes:
#    - $PWD/logs:/logs
#    - statsd

#api:
#  image: shubham1436/ms-blog-product-api-service
#  restart: always
#  volumes:
#    - $PWD/logs:/logs
#  links:
#    - auth
#    - config
#    - discovery
#    - rabbitmq
#    - statsd
 monitor:
   build: microservices/support/monitor-dashboard
   restart: always
   ports:
     - "7979:7979"

 edge:
   build: microservices/support/edge-server
   restart: always
   ports:
     - "443:8765"